spring:
    profiles:
        active: 
        - dev
---
spring:
    profiles: dev
    application:
        name: springcloud-config-yf-dev
---
spring:
   profiles: test
   application:
        name: springcloud-config-yf-test